const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync(require('node:path').join(__dirname,'../newsletter.js'),'utf8');
function harness(){
 const listeners={},timers=[],attributes={},events=[];let submitted=0,focused='',removed=false;
 function input(name,value=''){return {value,checked:false,setAttribute:(k,v)=>{attributes[name+k]=v;},removeAttribute:k=>delete attributes[name+k],focus:()=>focused=name,checkValidity(){return this.value.includes('@')&&this.value.includes('.');}};}
 const elements={email:input('email'),consent:input('consent'),started_at:input('started_at'),request_id:input('request_id')};
 const feedback={textContent:'',classList:{toggle(){}}},button={disabled:true,textContent:''},frameWindow={};
 const frame={contentWindow:frameWindow,setAttribute(){},remove(){removed=true;}};
 const form={elements,addEventListener:(type,fn)=>listeners[type]=fn,setAttribute:(k,v)=>attributes[k]=v,removeAttribute:k=>delete attributes[k],reset(){elements.email.value='';elements.consent.checked=false;}};
 const window={BRAMBLE_CONFIG:{newsletterEndpoint:'https://script.google.com/macros/s/test/exec'},crypto:{getRandomValues:a=>a.fill(12)},addEventListener:(type,fn)=>listeners[type]=fn,Bramble:{track:(...args)=>events.push(args)}};
 const ctx=vm.createContext({window,crypto:window.crypto,location:{hostname:'localhost',protocol:'http:'},document:{querySelector:s=>({'#newsletter-form':form,'#newsletter-submit':button,'#newsletter-status':feedback}[s]),createElement:()=>frame,body:{append(){}}},setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout(){},HTMLFormElement:{prototype:{submit(){submitted++;}}}});
 vm.runInContext(code,ctx);
 const submit=()=>listeners.submit({preventDefault(){}});
 const valid=()=>{elements.email.value=' Example@Test.com ';elements.consent.checked=true;elements.started_at.value=Date.now()-5000;submit();};
 const reply=(status,overrides={})=>listeners.message({origin:'https://test-script.googleusercontent.com',source:frameWindow,data:{type:'bramble-newsletter',requestId:elements.request_id.value,status},...overrides});
 return {elements,feedback,button,attributes,events,submit,valid,reply,timers,submitted:()=>submitted,focused:()=>focused,removed:()=>removed};
}
test('invalid email and missing consent show accessible errors and never submit',()=>{const h=harness();h.submit();assert.equal(h.attributes.emailariaInvalid,undefined);assert.equal(h.attributes['emailaria-invalid'],'true');assert.equal(h.focused(),'email');assert.match(h.feedback.textContent,/valid email/);h.elements.email.value='me@example.com';h.submit();assert.equal(h.attributes['consentaria-invalid'],'true');assert.equal(h.focused(),'consent');assert.equal(h.submitted(),0);});
test('pending state prevents double-submit and acknowledges success only after verified response',()=>{const h=harness();h.valid();assert.equal(h.submitted(),1);assert.equal(h.button.disabled,true);assert.equal(h.attributes['aria-busy'],'true');h.submit();assert.equal(h.submitted(),1);h.reply('success',{origin:'https://evil.example'});assert.equal(h.button.disabled,true);h.reply('success',{source:{}});assert.equal(h.button.disabled,true);h.reply('success',{data:{type:'bramble-newsletter',status:'success',requestId:'forged'}});assert.equal(h.button.disabled,true);h.reply('success');assert.equal(h.feedback.textContent,'You’re in. The next useful thing is headed your way.');assert.equal(h.button.disabled,false);assert.equal(h.button.textContent,'Send me the useful stuff');assert.equal(h.removed(),true);assert.equal(h.events[0][0],'newsletter_success');});
test('duplicate, server rejection and timeout restore usable form with honest feedback',()=>{for(const state of ['duplicate','invalid','rejected','busy','unavailable','error']){const h=harness();h.valid();h.reply(state);assert.equal(h.button.disabled,false);assert.ok(h.feedback.textContent.length>10);assert.equal(h.events.length,state==='duplicate'?1:0);}const h=harness();h.valid();h.timers[0]();assert.match(h.feedback.textContent,/couldn’t confirm/);assert.equal(h.button.disabled,false);});
